version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kang

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: kang
    depends_on:
      - db

volumes:
  mysql_data:
